management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # URL of Eureka Server
    register-with-eureka: true                     # Register with Eureka Server
    fetch-registry: true                            # Fetch registry from Eureka Server
    registry-fetch-interval-seconds: 10  # default 30
    lease-renewal-interval-in-seconds: 10  # how often client sends heartbeat (default 30)
    lease-expiration-duration-in-seconds: 30  # how long Eureka waits to expire a client (default 90)