# Kafka configuration
cloud:
  stream:
    default-binder: kafka
    bindings:
      sendToKafka-out-0: # Name of the binding
        destination: company-topic   # Kafka topic name
        group: company-consumer-group
        content-type: application/json
    kafka:
      binder:
        brokers: localhost:9092

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/company_db
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hikari Configuration
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: HikariCP
    max-lifetime: 2000000
    connection-timeout: 30000
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update  # or 'validate' or 'create' or 'create-drop' depending on your need
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always

resilience4j:
  circuitbreaker:
    instances:
      address-service:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 500ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # URL of Eureka Server
    register-with-eureka: true                     # Register with Eureka Server
    fetch-registry: true                            # Fetch registry from Eureka Server
    registry-fetch-interval-seconds: 10  # default 30
    lease-renewal-interval-in-seconds: 10  # how often client sends heartbeat (default 30)


  # Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
    consumer:
      group-id: company-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest

  # Database configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/company_db
      port: 27017
      database: company_db
      username: admin
      password: admin

employee:
  service:
    url: http://localhost:9090