# Kafka configuration
cloud:
  stream:
    default-binder: kafka
    bindings:
      sendToKafka-out-0: # Name of the binding
        destination: employee-topic   # Kafka topic name
        content-type: application/json
    kafka:
      binder:
        brokers: localhost:9092

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/employee_service_db
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hikari Configuration
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: HikariCP
    max-lifetime: 2000000
    connection-timeout: 30000

# JPA configuration
  jpa:
    hibernate:
      ddl-auto: update  # or 'validate' or 'create' or 'create-drop' depending on your need
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      enabled: true
  info:
    env:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        record-exceptions:
          - "feign.RetryableException"
          - "feign.FeignException"
          - "java.io.IOException"
          - "java.net.SocketTimeoutException"
        ignore-exceptions:
          - "org.springframework.web.client.HttpClientErrorException"
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 1
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 500ms

      departmentService:
        record-exceptions:
          - "feign.RetryableException"
          - "feign.FeignException"
          - "java.io.IOException"
          - "java.net.SocketTimeoutException"
        ignore-exceptions:
          - "org.springframework.web.client.HttpClientErrorException"
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 1
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 500ms

  retry:
    instances:
      addressService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - "feign.RetryableException"
          - "feign.FeignException"
          - "java.io.IOException"
          - "java.net.SocketTimeoutException"
        ignore-exceptions:
          - "org.springframework.web.client.HttpClientErrorException"

      departmentService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - "feign.RetryableException"
          - "feign.FeignException"
          - "java.io.IOException"
          - "java.net.SocketTimeoutException"
        ignore-exceptions:
          - "org.springframework.web.client.HttpClientErrorException"
service:
  url:
    address-service: http://localhost:9081/api/addresses
    department-service: http://localhost:9083/api/departments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # URL of Eureka Server
    register-with-eureka: true                     # Register with Eureka Server
    fetch-registry: true                            # Fetch registry from Eureka Server
    registry-fetch-interval-seconds: 10  # default 30
    lease-renewal-interval-in-seconds: 10  # how often client sends heartbeat (default 30)
    lease-expiration-duration-in-seconds: 30  # how long Eureka waits to expire a client (default 90)

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG